In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('BlackFriday.csv')

In [17]:
data.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [11]:
data.shape

(537577, 12)

In [12]:
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 537577 entries, 0 to 537576
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     537577 non-null  int64
 1   Product_ID                  537577 non-null  str
 2   Gender                      537577 non-null  str
 3   Age                         537577 non-null  str
 4   Occupation                  537577 non-null  int64
 5   City_Category               537577 non-null  str
 6   Stay_In_Current_City_Years  537577 non-null  str
 7   Marital_Status              537577 non-null  int64
 8   Product_Category_1          537577 non-null  int64
 9   Product_Category_2          370591 non-null  float64
 10  Product_Category_3          164278 non-null  float64
 11  Purchase                    537577 non-null  int64
dtypes: float64(2), int64(5), str(5)
memory usage: 163.0 MB

### Задачи

**1.** Сколько всего строк в датасете и сколько уникальных покупателей (`User_ID`)?

In [38]:
# Ваш код здесь
r = len(data)
u = data["User_ID"].unique()
u = len(u)
print(r,u)

537577 5891

In [14]:
# ответ: 537577, 5891

**2.** Сколько всего возрастных категорий? Какая возрастная категория встречается чаще всего и сколько?

In [67]:
# Ваш код здесь

a = data["Age"].unique()
a = len(a)
value_index = data["Age"].value_counts()
most_age = value_index.index[0]
count = value_index.values[0]
print(a,most_age,count)

7 26-35 214690

In [16]:
# ответ: 7, 26-35, 214690

**3.** Сколько строк с мужчинами из категории города A? (речь не об уникальных ID мужчин, а о количестве строк)

In [76]:
# Ваш код здесь
a = data[(data["Gender"] == "M")&(data["City_Category"] == "A")]

len(a)

109831

In [10]:
# ответ: 109831

**4.** Сколько женщин от 46 до 50, потративших (столбец `Purchase`) больше 20000 (условных единиц, в данном случае)?   (речь не об уникальных ID, а о количестве строк)

In [99]:
# Ваш код здесь
a = data[(data["Gender"] == "F") & (data["Age"].between("46", "50"))]
len(a[a["Purchase"] > 20000])

270

In [12]:
# ответ: 270

**5.** Какой средний `Purchase` у мужчин и у женщин (округлите до двух знаков после запятой)?

In [109]:
# # Ваш код здесь
# men = data[(data["Gender"] == "M")]
# men_mean = men["Purchase"].mean().round(2)
# female = data[(data["Gender"] == "F")]
# female_mean = female["Purchase"].mean().round(2)
# print(men_mean,female_mean)
result = data.groupby("Gender")["Purchase"].mean().round(2)
result

Gender
F    8809.76
M    9504.77
Name: Purchase, dtype: float64

In [14]:
# ответ: женщины: 8809.76, мужчины: 9504.77

**6.** Сколько `NaN`-ов в столбце `Product_Category_3`?

In [118]:
# Ваш код здесь
data["Product_Category_3"].isnull().sum()

np.int64(373299)

In [16]:
# ответ: 373299

**7.** В каком типе города (`City_Category`) самый высокий средний чек (`Purchase`) и сколько (округлите до двух знаков после запятой)?

In [80]:
# Ваш код здесь

result = data.groupby("City_Category")["Purchase"].mean().round(2)
sorted_result = result.sort_values(ascending=False)
sorted_result.head(1)

City_Category
C    9844.44
Name: Purchase, dtype: float64

In [18]:
# ответ: С, 9844.44

**8.** Сколько уникальных товаров (`Product_ID`) купили женщины 18–25 лет?

In [159]:
# Ваш код здесь
a = data[(data["Gender"] == "F") & (data["Age"].between("18", "25"))]
len(a["Product_ID"].unique())

2600

In [20]:
# ответ: 2600

**9.** Какая категория товара первого уровня (`Product_Category_1`) принесла наибольшую суммарную выручку (`Purchase`)?

In [176]:
# Ваш код здесь

category = data.groupby("Product_Category_1")["Purchase"].sum()
print(category.head(1))

Product_Category_1
1    1882666325
Name: Purchase, dtype: int64

In [22]:
# ответ: 1882666325

**10.** У какой возрастной группы самый высокий средний чек (`Purchase`) и сколько (округлите до двух знаков после запятой)?

In [196]:
age = data.groupby("Age")["Purchase"].mean().round(2)
age.sort_values(ascending=False).head(1)

Age
51-55    9620.62
Name: Purchase, dtype: float64

In [24]:
# ответ: 51-55, 9620.62

**11.** Какую долю всех строк составляют покупки из города `C`?

In [211]:
# Ваш код здесь
city_c_count = len(data[data["City_Category"] == "C"])
total_Count = len(data)

persend = ( city_c_count)/ total_Count

persend

0.30962262150352415

In [26]:
# ответ: 0.3096

**12.** У кого медианная покупка выше: у состоящих в браке или не состоящих? Сколько?

In [26]:
# Ваш код здесь

m = data.groupby(data["Marital_Status"])["Purchase"].median().round(2)

m

Marital_Status
0    8059.0
1    8066.0
Name: Purchase, dtype: float64

In [28]:
# ответ: у состоящих в браке (1)

**13.** Какой пользователь (`User_ID`) потратил больше всего суммарно и сколько?

In [34]:
# Ваш код здесь


u = data.groupby("User_ID")["Purchase"].sum()

u.sort_values(ascending=False).nlargest(1)

User_ID
1004277    10536783
Name: Purchase, dtype: int64

In [30]:
# ответ: User_ID: 1004277, cумма 10536783

**14.** Какую долю (вещественное число от 0 до 1, округлить до 4-го знака) от всех покупателей составляют ВМЕСТЕ мужчины от 26 до 35 лет и женщины старше 36 лет (то есть нужно учесть несколько возрастных категорий)? (речь не об уникальных ID, а о количестве таких строк)

In [47]:
# Ваш код здесь
m = data[(data["Gender"] == "M")& (data["Age"].between("26","35"))]
f = data[(data["Gender"] == "F")& (data["Age"] >= "36")]
len_data = len(data)

res = (len(m) + len(f))/len_data
round(res,4)

0.4077

In [32]:
# ответ: 0.4077

**15.** Найти топ-5 пользователей по суммарным тратам.

In [54]:
# Ваш код здесь

top = data.groupby("User_ID")["Purchase"].sum()
top.sort_values(ascending=False).nlargest(5)

User_ID
1004277    10536783
1001680     8699232
1002909     7577505
1001941     6817493
1000424     6573609
Name: Purchase, dtype: int64

In [34]:
# ответ:

# User_ID    Purchase sum
# 1004277    10536783
# 1001680     8699232
# 1002909     7577505
# 1001941     6817493
# 1000424     6573609

**16.** Для каждой возрастной группы посчитать долю мужчин и женщин в процентах (округлите до двух знаков после запятой).

In [73]:
p = data.groupby("Age")["Gender"].value_counts(normalize=True)


r = (p * 100).unstack().round(2)
r

Gender      F      M
Age
0-17    33.68  66.32
18-25   24.64  75.36
26-35   22.99  77.01
36-45   24.58  75.42
46-50   28.87  71.13
51-55   25.61  74.39
55+     23.58  76.42

In [36]:
# ответ:

# Gender	F	    M
# Age		
# 0-17	  33.68	  66.32
# 18-25	  24.64	  75.36
# 26-35	  22.99	  77.01
# 36-45	  24.58	  75.42
# 46-50	  28.87	  71.13
# 51-55	  25.61	  74.39
# 55+	  23.58	  76.42

**17.** Найти товар (`Product_ID`), который чаще всего покупали. Найти сколько всего покупали этот товар.

In [21]:
# Ваш код здесь
prod = data["Product_ID"].value_counts()
prod.nlargest(1)

Product_ID
P00265242    1858
Name: count, dtype: int64

In [38]:
# ответ: Product_ID - P00265242, количество - 1858

**18.** Посчитать средний чек по комбинации `Gender + City_Category` (округлите до двух знаков после запятой).

In [35]:
# Ваш код здесь
m =data.groupby(["Gender", "City_Category"])["Purchase"].mean().round(2)
m

Gender  City_Category
F       A                 8630.77
        B                 8590.52
        C                 9264.96
M       A                 9061.72
        B                 9400.75
        C                10033.20
Name: Purchase, dtype: float64

In [40]:
# ответ:

# Gender  City_Category
# F       A                 8630.77
#         B                 8590.52
#         C                 9264.96
# M       A                 9061.72
#         B                 9400.75
#         C                10033.20

**19.** Найти категорию `Product_Category_1`, у которой больше всего пропусков в `Product_Category_2` и найти количество этих пропусков.

In [60]:
# Ваш код здесь
a =data[data["Product_Category_2"].isna()]
a["Product_Category_1"].value_counts().nlargest(1)

Product_Category_1
5    62788
Name: count, dtype: int64

In [42]:
# ответ: 5, 62788

**20.** Для каждого города найти самую популярную возрастную группу и их количества.

In [79]:
# Ваш код здесь
age = data.groupby("City_Category")["Age"].value_counts().sort_values(ascending=False).head(3)

age.sort_index()

City_Category  Age
A              26-35    72048
B              26-35    89767
C              26-35    52875
Name: count, dtype: int64

In [44]:
# ответ:

# City_Category   Age    count
# A              26-35   72048
# B              26-35   89767
# C              26-35   52875

City_Category
A    0-170-170-170-1726-3526-3526-3526-3526-3526-35...
B    46-5046-5046-5036-4536-4536-4536-4536-4536-453...
C    55+26-3526-3526-3526-3526-3526-3526-3526-3526-...
Name: Age, dtype: str