In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import PolynomialFeatures,MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("taxi_trip_pricing.csv")
data

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,Afternoon,Weekend,4.0,Medium,Clear,2.39,0.62,0.49,58.39,34.4049
996,45.95,Night,Weekday,4.0,Medium,Clear,3.12,0.61,NaN,61.96,62.1295
997,7.70,Morning,Weekday,3.0,Low,Rain,2.08,1.78,NaN,54.18,33.1236
998,47.56,Morning,Weekday,1.0,Low,Clear,2.67,0.82,0.17,114.94,61.2090
999,22.85,Morning,Weekend,3.0,Medium,Clear,4.34,NaN,0.23,29.69,45.4437

In [3]:
data.isna().sum()

Trip_Distance_km         50
Time_of_Day              50
Day_of_Week              50
Passenger_Count          50
Traffic_Conditions       50
Weather                  50
Base_Fare                50
Per_Km_Rate              50
Per_Minute_Rate          50
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [4]:

data = data.dropna(subset=['Trip_Price'])

In [5]:
x = data.drop("Trip_Price",axis=1)
y= data["Trip_Price"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x,y ,test_size=0.2)

In [7]:
Trip_Distance_km_median = X_train['Trip_Distance_km'].median()
X_train['Trip_Distance_km'] = X_train["Trip_Distance_km"].fillna(Trip_Distance_km_median)
X_test['Trip_Distance_km'] = X_test["Trip_Distance_km"].fillna(Trip_Distance_km_median)

In [8]:
X_train.isna().sum() ,X_test.isna().sum()

(Trip_Distance_km          0
 Time_of_Day              42
 Day_of_Week              38
 Passenger_Count          40
 Traffic_Conditions       35
 Weather                  38
 Base_Fare                38
 Per_Km_Rate              36
 Per_Minute_Rate          34
 Trip_Duration_Minutes    29
 dtype: int64,
 Trip_Distance_km          0
 Time_of_Day               7
 Day_of_Week               8
 Passenger_Count           8
 Traffic_Conditions       15
 Weather                   8
 Base_Fare                 6
 Per_Km_Rate               8
 Per_Minute_Rate          15
 Trip_Duration_Minutes    17
 dtype: int64)

In [9]:
Time_of_Day_mode = X_train["Time_of_Day"].mode()[0]
X_train['Time_of_Day'] = X_train["Time_of_Day"].fillna(Time_of_Day_mode)
X_test['Time_of_Day'] = X_test["Time_of_Day"].fillna(Time_of_Day_mode)

In [10]:
X_train = pd.get_dummies(X_train, columns=['Time_of_Day'])
X_test = pd.get_dummies(X_test, columns=['Time_of_Day'])

In [11]:

Day_of_Week_mode = X_train["Day_of_Week"].mode()[0]
X_train['Day_of_Week'] = X_train["Day_of_Week"].fillna(Day_of_Week_mode)
X_test['Day_of_Week'] = X_test["Day_of_Week"].fillna(Day_of_Week_mode)

In [12]:
X_train["Day_of_Week Activities"] = (X_train["Day_of_Week"] == "").astype('int8')

In [13]:
X_train = pd.get_dummies(X_train, columns=['Day_of_Week'])
X_test = pd.get_dummies(X_test, columns=['Day_of_Week'])

In [14]:
X_test

,Trip_Distance_km,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Time_of_Day_Afternoon,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Day_of_Week_Weekday,Day_of_Week_Weekend
626,23.66,3.0,Medium,Clear,3.53,0.61,0.15,52.82,False,False,True,False,True,False
159,36.68,3.0,High,Rain,3.89,0.94,0.36,106.25,True,False,False,False,False,True
155,12.86,1.0,Low,Clear,2.39,1.13,0.40,56.62,False,True,False,False,True,False
491,31.39,1.0,Low,Clear,3.63,0.86,0.19,28.43,True,False,False,False,True,False
989,41.14,3.0,Medium,Rain,4.14,1.71,0.17,46.78,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,44.94,1.0,Low,Clear,2.61,1.04,0.31,64.02,False,True,False,False,True,False
731,40.91,1.0,Medium,Clear,4.73,1.16,0.28,19.10,True,False,False,False,True,False
851,37.75,2.0,Medium,Snow,3.55,0.56,0.12,44.99,False,True,False,False,True,False
543,33.91,2.0,Medium,Clear,2.48,0.73,0.38,34.54,False,False,True,False,True,False
877,33.29,3.0,High,Clear,4.48,1.10,0.19,52.09,True,False,False,False,True,False

In [ ]:
# Կիրառում ենք One-Hot Encoding
X_train = pd.get_dummies(X_train, columns=['Weather'], dtype=int)
X_test = pd.get_dummies(X_test, columns=['Weather'], dtype=int)